app = "bharatverse"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.streamlit"

[env]
  AI_MODE = "free_tier"
  USE_LIGHTWEIGHT_MODELS = "true"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"