# 🚀 STREAMLIT CLOUD PRODUCTION SECRETS
# Copy this EXACTLY to: Streamlit Cloud → Your App → Settings → Secrets

# ============================================================================
# STEP 1: Replace these with YOUR GitLab OAuth credentials
# ============================================================================
[gitlab]
client_id = "REPLACE_WITH_YOUR_GITLAB_APPLICATION_ID"
client_secret = "REPLACE_WITH_YOUR_GITLAB_APPLICATION_SECRET"
base_url = "https://code.swecha.org"
scopes = "api read_user profile email"

# ============================================================================
# STEP 2: Production Configuration (DO NOT CHANGE)
# ============================================================================
[general]
APP_ENV = "streamlit"
DEPLOYMENT_MODE = "cloud"
AI_MODE = "cloud"
DISABLE_GITLAB_AUTH = "false"

# Security
[security]
SECRET_KEY = "bharatverse-prod-2025-secure-key-change-in-real-production"
SESSION_TIMEOUT = "3600"

# Features (Enable all for production)
[features]
ENABLE_AUDIO_CAPTURE = "true"
ENABLE_TEXT_STORIES = "true"
ENABLE_VISUAL_HERITAGE = "true"
ENABLE_AI_INSIGHTS = "true"
ENABLE_COMMUNITY_FEATURES = "true"
ENABLE_GITLAB_INTEGRATION = "true"

# Performance
[performance]
CACHE_TTL_HOURS = "24"
MAX_UPLOAD_SIZE_MB = "50"
ENABLE_CACHING = "true"

# ============================================================================
# OPTIONAL: Advanced Features (Leave empty if not using)
# ============================================================================

# Database (Optional - for user data persistence)
[database]
# DATABASE_URL = "postgresql://user:pass@host:port/dbname"

# Redis (Optional - for caching)
[redis]
# REDIS_URL = "redis://user:pass@host:port"

# AI APIs (Optional - for enhanced features)
[ai]
# HUGGINGFACE_TOKEN = "hf_your_token_here"
# OPENAI_API_KEY = "sk-your-openai-key"

# ============================================================================
# INSTRUCTIONS:
# 1. Create GitLab OAuth app at: https://code.swecha.org/profile/applications
# 2. Set Redirect URI to: https://amruth-bharatverse.streamlit.app/callback
# 3. Replace client_id and client_secret above with your real values
# 4. Copy this entire file content to Streamlit Cloud Secrets
# 5. Deploy!
# ============================================================================