
# Streamlit Secrets Template for BharatVerse Free Cloud Deployment
# Copy to Streamlit Cloud Secrets: https://share.streamlit.io -> Your App -> Settings -> Secrets

# Database Configuration (Supabase PostgreSQL - Free Tier)
[postgres]
host = "db.<your-project-id>.supabase.co"
port = "5432"
database = "postgres"
user = "postgres"
password = "your-supabase-password"

# Redis Configuration (Upstash Redis - Free Tier)
[redis]
url = "redis://:your-upstash-token@your-endpoint.upstash.io:port"

# Object Storage Configuration (Cloudflare R2 - Free Tier)
[r2]
endpoint_url = "https://<account-id>.r2.cloudflarestorage.com"
aws_access_key_id = "your-r2-access-key"
aws_secret_access_key = "your-r2-secret-key" 
bucket_name = "bharatverse-files"
public_url = "https://your-custom-domain.com"  # Optional custom domain
region = "auto"

# AI Inference APIs (Free Tier Options)
[inference]
# Hugging Face (Free tier with rate limits)
huggingface_token = "hf_your_token_here"

# Audio Processing (Whisper)
whisper_api = "https://api-inference.huggingface.co/models/openai/whisper-large-v3"

# Text Analysis 
text_analysis_api = "https://api-inference.huggingface.co/models/cardiffnlp/twitter-roberta-base-sentiment-latest"

# Image Analysis
image_analysis_api = "https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-large"

# Translation
translation_api = "https://api-inference.huggingface.co/models/facebook/nllb-200-distilled-600M"

# RunPod (Optional - for heavier models)
runpod_token = ""  # Leave empty if not using RunPod

# Authentication & Security
[auth]
secret_key = "bharatverse-super-secret-key-change-this-in-production"
algorithm = "HS256"
access_token_expire_minutes = "1440"

# Application Settings
[app]
environment = "cloud"
debug = false
max_upload_size = "50"  # MB - Keep low for free tiers
enable_caching = true
cache_ttl_hours = "24"

# Rate Limiting (to stay within free tier limits)
[rate_limits]
api_calls_per_minute = "60"
uploads_per_hour = "100"
max_concurrent_users = "50"
