
# Copy these to Streamlit Cloud Secrets
# Go to: https://share.streamlit.io -> Your App -> Settings -> Secrets

POSTGRES_HOST = "your-tunnel-url"
POSTGRES_PORT = "5432"
POSTGRES_USER = "bharatverse_user"
POSTGRES_PASSWORD = "secretpassword"
POSTGRES_DB = "bharatverse"

REDIS_HOST = "your-tunnel-url"
REDIS_PORT = "6379"

MINIO_HOST = "your-tunnel-url:9000"
MINIO_ACCESS_KEY = "minioadmin"
MINIO_SECRET_KEY = "minioadmin"

API_URL = "https://your-tunnel-url:8000"

SECRET_KEY = "your-secret-key-here"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"

AI_MODE = "cloud"
ENABLE_HEAVY_MODELS = "false"
USE_LIGHTWEIGHT_MODELS = "true"
