# 🚀 MINIMAL STREAMLIT SECRETS - IMMEDIATE DEPLOYMENT
# Copy this to get your app working RIGHT NOW (no OAuth setup needed)

[general]
APP_ENV = "streamlit"
DEPLOYMENT_MODE = "cloud"
AI_MODE = "cloud"
DISABLE_GITLAB_AUTH = "true"

[security]
SECRET_KEY = "bharatverse-minimal-deployment-key-2025"

[features]
ENABLE_AUDIO_CAPTURE = "true"
ENABLE_TEXT_STORIES = "true"
ENABLE_VISUAL_HERITAGE = "true"
ENABLE_AI_INSIGHTS = "true"
ENABLE_COMMUNITY_FEATURES = "true"

# ============================================================================
# INSTRUCTIONS FOR IMMEDIATE DEPLOYMENT:
# 1. Copy this entire content
# 2. Go to Streamlit Cloud → Your App → Settings → Secrets
# 3. Paste this content
# 4. Save
# 5. Your app will work in 2 minutes!
# 
# Note: This disables GitLab OAuth, so no login required
# Users can access all features without authentication
# Perfect for demos and testing!
# ============================================================================