[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFEAA7"
secondaryBackgroundColor = "#FDCB6E"
textColor = "#2D3436"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false
