[global]
# Performance optimizations
developmentMode = false
showWarningOnDirectExecution = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#2D3436"
font = "sans serif"

[server]
# Server optimizations
headless = true
runOnSave = false
allowRunOnSave = false
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true

[browser]
# Browser optimizations
gatherUsageStats = false
showErrorDetails = false

[client]
# Client optimizations
caching = true
displayEnabled = true
toolbarMode = "minimal"

[runner]
# Runner optimizations
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[logger]
# Logging optimizations
level = "INFO"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
# Disable deprecation warnings for performance
showPyplotGlobalUse = false
showfileUploaderEncoding = false
