[theme]
# BharatVerse theme configuration
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# Server configuration for Streamlit Cloud
headless = true
maxUploadSize = 100
maxMessageSize = 100
enableWebsocketCompression = true
enableCORS = true
enableXsrfProtection = true

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = ""
serverPort = 8501

[client]
# Client configuration
caching = true
displayEnabled = true
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true

[logger]
# Logging configuration
level = "INFO"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
# Deprecation warnings
showPyplotGlobalUse = false
showfileUploaderEncoding = false
